In [46]:
%matplotlib widget
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv

In [47]:
data = pd.read_csv("cleaned_data.csv", parse_dates=["datetime"])

In [29]:
data

,id,start_time,end_time,time_diff,x_dir,y_dir,start_frame,end_frame,frame_diff,calculated_time,calculated_distance,speed_mps,speed_kmh,avg_size,datetime
0,7.0,1.621269e+09,1.621269e+09,1.518,-1.0,-1.0,1387.0,1409.0,22.0,1.467,13.218,9.01,32.44,6681.0,2021-05-17 18:34:54.666
1,19.0,1.621269e+09,1.621269e+09,2.746,-1.0,1.0,2304.0,2345.0,41.0,2.733,13.762,5.03,18.11,4565.0,2021-05-17 18:35:55.877
2,37.0,1.621270e+09,1.621270e+09,1.670,-1.0,-1.0,6171.0,6196.0,25.0,1.667,13.871,8.32,29.95,6843.0,2021-05-17 18:40:13.579
3,38.0,1.621270e+09,1.621270e+09,2.318,-1.0,-1.0,7028.0,7063.0,35.0,2.333,13.615,5.84,21.02,5793.0,2021-05-17 18:41:10.730
4,57.0,1.621270e+09,1.621270e+09,1.864,-1.0,-1.0,8051.0,8079.0,28.0,1.867,13.138,7.04,25.34,7604.0,2021-05-17 18:42:18.928
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8322,29092.0,1.622142e+09,1.622142e+09,2.261,-1.0,-1.0,1253144.0,1253178.0,34.0,2.267,13.620,6.01,21.64,9618.0,2021-05-27 20:54:40.302
8323,29128.0,1.622142e+09,1.622142e+09,2.013,-1.0,-1.0,1253802.0,1253832.0,30.0,2.000,13.739,6.87,24.73,6444.0,2021-05-27 20:55:24.160
8324,29136.0,1.622142e+09,1.622142e+09,1.592,-1.0,-1.0,1254920.0,1254944.0,24.0,1.600,13.850,8.66,31.18,8609.0,2021-05-27 20:56:38.697
8325,29140.0,1.622142e+09,1.622142e+09,2.080,-1.0,-1.0,1255772.0,1255803.0,31.0,2.067,13.813,6.68,24.05,7877.0,2021-05-27 20:57:35.492
8326,29142.0,1.622142e+09,1.622142e+09,2.800,-1.0,-1.0,1257330.0,1257372.0,42.0,2.800,13.739,4.91,17.68,6848.0,2021-05-27 20:59:19.370

In [30]:
data[["id", "time_diff", "x_dir", "y_dir", "frame_diff", "calculated_time", "calculated_distance", "speed_mps", "speed_kmh", "avg_size"]].describe()

,id,time_diff,x_dir,y_dir,frame_diff,calculated_time,calculated_distance,speed_mps,speed_kmh,avg_size
count,8327.000000,8327.000000,8327.000000,8327.000000,8327.000000,8327.000000,8327.000000,8327.000000,8327.000000,8327.000000
mean,15216.605981,2.060210,-0.993275,-0.933830,30.931668,2.062110,13.652838,7.339281,26.421440,7564.879428
std,12132.096735,0.807925,0.115787,0.356562,12.110936,0.807395,0.472729,2.126405,7.655146,2284.664951
min,1.000000,0.589000,-1.000000,-1.000000,9.000000,0.600000,9.624000,1.050000,3.780000,2507.000000
25%,5492.000000,1.578000,-1.000000,-1.000000,24.000000,1.600000,13.541000,5.970000,21.490000,6104.500000
50%,12055.000000,1.866000,-1.000000,-1.000000,28.000000,1.867000,13.699000,7.320000,26.350000,7373.000000
75%,22113.500000,2.275500,-1.000000,-1.000000,34.000000,2.267000,13.850000,8.680000,31.250000,8750.500000
max,50185.000000,11.401000,1.000000,1.000000,171.000000,11.400000,17.167000,22.010000,79.240000,14992.000000

In [31]:
data[["id", "time_diff","calculated_time", "frame_diff", "calculated_distance", "speed_mps", "speed_kmh", "avg_size"]].sort_values("speed_kmh", ascending=False)

,id,time_diff,calculated_time,frame_diff,calculated_distance,speed_mps,speed_kmh,avg_size
2555,27877.0,0.614,0.600,9.0,13.207,22.01,79.24,3144.0
6107,28114.0,0.605,0.600,9.0,11.969,19.95,71.82,3825.0
1143,19655.0,0.589,0.600,9.0,11.397,19.00,68.40,9138.0
7239,8072.0,0.729,0.733,11.0,13.696,18.68,67.25,4004.0
8104,26459.0,0.673,0.667,10.0,12.065,18.10,65.16,6709.0
...,...,...,...,...,...,...,...,...
747,8517.0,9.339,9.333,140.0,13.040,1.40,5.04,4661.0
7423,11261.0,10.077,10.067,151.0,13.694,1.36,4.90,5481.0
826,11602.0,9.600,9.600,144.0,13.080,1.36,4.90,3457.0
507,27152.0,11.401,11.400,171.0,12.712,1.12,4.03,4506.0
611,2247.0,9.414,9.400,141.0,9.866,1.05,3.78,2963.0

In [32]:
bins = [i for i in range(0, 70, 1)]
plt.figure(0)
data[data.speed_kmh > 35][["speed_kmh"]].plot.hist("speed_kmh", bins=bins, color="red", legend=None, edgecolor="white")
data[data.speed_kmh <= 35].speed_kmh.plot.hist("speed_kmh", bins=bins, color="green", edgecolor="white")
plt.xlabel("speed km/h")

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous â€¦

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous â€¦

Text(0.5, 0, 'speed km/h')

In [52]:
plt.figure(1)
hours = data["datetime"].dt.hour
minutes = data.datetime.dt.minute
bins = [i for i in range(6, 22)]
data.datetime.dt.hour.plot.hist(edgecolor="white")

In [8]:
len(data[data.speed_kmh > 35])/len(data.speed_kmh) * 100

12.36940074456587

In [9]:
len(data[data.speed_kmh < 20])

1634

In [10]:
data.plot.scatter("avg_size", "speed_kmh", alpha=0.2)

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous â€¦

In [51]:
# Average speed per hour
speed_sum_per_hour = data.groupby(data.datetime.dt.hour).agg('sum').speed_kmh
ocassions_per_hour = data.groupby(data.datetime.dt.hour).count().datetime
average_speed_per_hour = speed_sum_per_hour / ocassions_per_hour
average_speed_per_hour.plot.bar(xlabel="Hour of day", ylabel="Speed km/h")
plt.xlabel("Hour of day")
plt.ylabel("Speed km/h")

Text(37.06944598754247, 0.5, 'Speed km/h')